apiVersion: v1
kind: Service
metadata:
  name: taskmanager
  namespace: deployforge
  labels:
    app: taskmanager
    app.kubernetes.io/name: taskmanager
spec:
  type: ClusterIP
  selector:
    app: taskmanager
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
